### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [MykhailoBobrovnikov/HomeWorkMB#1]
1)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/123521352-cf996900-d6be-11eb-8e7b-c5cc6247736a.png)

2)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/123521383-f0fa5500-d6be-11eb-920a-a2eda786f8ef.png)

**Comment by Alecto** [comment]
3)
положение не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/123533879-a1994080-d721-11eb-8a6c-98436e0b3f4a.png)

4)
некорректный вид
![image](https://user-images.githubusercontent.com/8464662/123533895-bd9ce200-d721-11eb-95e9-670f078c5bd4.png)


5)
неправильный шрифт
![image](https://user-images.githubusercontent.com/8464662/123533901-c55c8680-d721-11eb-9047-10dd6245fcf1.png)

6)
неправильный вид 
![image](https://user-images.githubusercontent.com/8464662/123533907-d6a59300-d721-11eb-9050-7e9a3f2e1331.png)


7)
неправильное оформление
![image](https://user-images.githubusercontent.com/8464662/123533915-e7560900-d721-11eb-930e-28d75153e051.png)

**Comment by MykhailoBobrovnikov** [comment]
Mykhailo Bobrovnikov ***@***.***>
сб, 26 июн., 22:50 (3 дня назад)
кому: Андрей
Добрый вечер !

Исправил ошибки !

https://github.com/MykhailoBobrovnikov/HomeWorkMB

https://mykhailobobrovnikov.github.io/HomeWorkMB/

вс, 27 июн. 2021 г. в 08:31, Andrey ***@***.***>:

**Comment by Alecto** [comment]
8)
неправильный вид
![image](https://user-images.githubusercontent.com/8464662/123814593-7a4b9a80-d8fe-11eb-806a-4152a98dfca0.png)

**Comment by MykhailoBobrovnikov** [comment]
Добрый вечер !

Исправил положение меню  !

https://github.com/MykhailoBobrovnikov/HomeWorkMB

https://mykhailobobrovnikov.github.io/HomeWorkMB/

вт, 29 июн. 2021 г. в 17:22, Andrey ***@***.***>:

**Comment by Alecto** [comment]
хорошо, работа принята

вт, 29 июн. 2021 г. в 18:08, Mykhailo ***@***.***>:
